import logging
from typing import Optional

from pydantic import field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

logger = logging.getLogger(__name__)


class Settings(BaseSettings):
    """Application settings with support for development and production environments.

    Environment Variables:
    - ENV: "development" or "production" (default: "development")
    - .env file loading: .env.dev for development, .env.prod for production
    - Service names: docker-compose service names for development
    - Railway variables: auto-generated by Railway for production
    """

    # ============= ENVIRONMENT =============
    ENV: str = "development"  # "development" or "production"

    # ============= CORE SETTINGS =============
    SECRET_KEY: str = "your-secret-key-change-in-production"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 30
    REFRESH_TOKEN_EXPIRE_DAYS: int = 7
    ALGORITHM: str = "HS256"
    DEBUG: bool = True  # Set to False in production

    # ============= DATABASE CONFIGURATION =============
    # Development: "postgresql://postgres:password@postgres:5432/appdb" (docker-compose service name)
    # Production: Railway auto-generates from PostgreSQL plugin
    DATABASE_URL: str = "postgresql+asyncpg://postgres:password@postgres:5432/appdb"
    POSTGRES_PASSWORD: Optional[str] = None

    @field_validator("DATABASE_URL", mode="after")
    @classmethod
    def validate_database_url(cls, v: str) -> str:
        """Ensure DATABASE_URL uses asyncpg driver for async support."""
        if v and "postgresql://" in v and "+asyncpg" not in v:
            v = v.replace("postgresql://", "postgresql+asyncpg://")
        return v

    # ============= EMAIL CONFIGURATION (SendGrid) =============
    SENDGRID_API_KEY: str = ""  # Get from https://sendgrid.com (format: SG.xxxxx)
    SENDGRID_FROM_EMAIL: str = "trongtuyenlekhiet@gmail.com"
    EMAIL_DISPATCHER: str = "celery"  # "background_tasks" or "celery"

    # ============= REDIS & CELERY CONFIGURATION =============
    # Development: "redis://redis:6379/0" (docker-compose service name)
    # Production: Railway auto-generates from Redis plugin
    REDIS_URL: str = "redis://redis:6379/0"
    # These will be derived from REDIS_URL in model_post_init
    CELERY_BROKER_URL: str = "redis://redis:6379/0"
    CELERY_RESULT_BACKEND: str = "redis://redis:6379/1"

    # ============= TESTING MODE =============
    TEST_MODE: bool = False
    FAKE_EMAIL_FAILURE: bool = False
    FAKE_FAILURE_RATE: float = 0.5

    # ============= PYDANTIC CONFIGURATION =============
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
        case_sensitive=False,
    )

    def model_post_init(self, __context):
        """Post-initialization: derive Celery URLs from REDIS_URL.

        Railway sets only REDIS_URL, so we derive BROKER_URL and RESULT_BACKEND.
        This ensures Celery always uses correct Redis configuration.
        """
        if self.REDIS_URL:
            # Extract base Redis URL (remove database index if present)
            # e.g., "redis://redis:6379/0" → "redis://redis:6379"
            base_redis = self.REDIS_URL
            # Remove trailing /[0-9]+ if present
            if "/" in base_redis:
                parts = base_redis.rsplit("/", 1)
                if len(parts) == 2 and parts[1].isdigit():
                    base_redis = parts[0]

            # Set Celery URLs with proper database indices
            self.CELERY_BROKER_URL = f"{base_redis}/0"
            self.CELERY_RESULT_BACKEND = f"{base_redis}/1"

            logger.info(f"[CONFIG] Celery broker: {self.CELERY_BROKER_URL}")
            logger.info(f"[CONFIG] Celery backend: {self.CELERY_RESULT_BACKEND}")

    def __init__(self, **data):
        super().__init__(**data)
        # Log environment info
        logger.info(f"[CONFIG] Environment: {self.ENV}")
        logger.info(f"[CONFIG] Debug mode: {self.DEBUG}")
        logger.info(
            f"[CONFIG] Database: {self.DATABASE_URL.split('@')[1] if '@' in self.DATABASE_URL else 'hidden'}"
        )


settings = Settings()
